[jenkins_controllers]
jenkins-controller ansible_host=192.168.122.20

[podman_hosts]
podman-host ansible_host=192.168.122.21

[jenkins_lab:children]
jenkins_controllers
podman_hosts

# Variables aplicadas a todos los nodos del laboratorio
[jenkins_lab:vars]
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
ansible_python_interpreter=/usr/bin/python3
